apiVersion: apps/v1
kind: Deployment
metadata:
  name: melih
  labels:
    product: actimize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: melih
      tier: web
  template:
    metadata:
      labels:
        app: melih
        tier: web
    spec:
      containers:
      - name: springboot-image-container
        image: melihcetin/springboot-image
        ports:
        - containerPort: 8080
        resources:
          limits:  
            cpu: 1000m
            memory: 600Mi             
          requests: 
            cpu: 500m
            memory: 300Mi
